Changes to "Atomist enables" section
chingu-voyages/v8-toucans-team-04 pull request #16
Opened 2019-04-01 03:35 UTC by sarajoha

Hi guys! I made these changes:

- Switched placeholder images for real ones.
- Changed background color.
- Adjusted width of the cards. 
- Changes button color.

2019-04-01 14:49 UTC, Brazill-Mitchell requested changes
Your changes look great!
Just one thing, there's some CSS that seems to be missing. It looks like you'll need to pull the CSS file and update your PR. Then it should be good to go!

2019-04-01 17:11 UTC, corochena approved these changes
I am eager to see it online

2019-04-02 02:18 UTC, brazill91 commented
Perfect!

2019-04-02 02:19 UTC, Brazill-Mitchell approved these changes

2019-04-02 02:19 UTC, merged